<?php

/**
 * @file
 * This modules provides New Relic fuctions missing from a CI/CD environment.
 */

/**
 * Provides testable response for missing NR function.
 *
 * @return string
 *   Test string response.
 */
// phpcs:ignore
function newrelic_get_browser_timing_header() {
  return "<script>console.log('header script inserted')</script>";
}

/**
 * Provides testable response for missing NR function.
 *
 * @return string
 *   Test string response.
 */
// phpcs:ignore
function newrelic_get_browser_timing_footer() {
  return "<script>console.log('footer script inserted')</script>";
}
